name: ShiftChiro
favicon: null
layout_spectrum: 0.4951
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060800'
    - '#1b370e'
    - '#87a448'
    - '#b7de6b'
    - '#edefa5'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
